"""empty message

Revision ID: c8253da31763
Revises: 
Create Date: 2024-10-30 02:38:31.954104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8253da31763'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk__message__user_id', 'message', type_='foreignkey')
    op.create_foreign_key('fk__message__user_id', 'message', 'user', ['user_id'], ['user_id'], ondelete='cascade')
    op.drop_constraint('fk__session__user_id', 'session', type_='foreignkey')
    op.create_foreign_key('fk__session__user_id', 'session', 'user', ['user_id'], ['user_id'], ondelete='cascade')
    op.add_column('user', sa.Column('user_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_id')
    op.drop_constraint('fk__session__user_id', 'session', type_='foreignkey')
    op.create_foreign_key('fk__session__user_id', 'session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk__message__user_id', 'message', type_='foreignkey')
    op.create_foreign_key('fk__message__user_id', 'message', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
